# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 04e78a5407d4db2cc6a8d777be55a818b4a285f5a29c6437a7630aea837dbf8cd060346e317824cddbfc748b02af91baa8989b629c969d57e41e6c5666832502

test:
  secret_key_base: 0897d7114c715173df9af8cbd13a712962d2432f9033241451d3095330f340de5b7df5ee4233856d899751924f465994f48e2827fa11230797f0b23c347a782a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
